knp_paginator:
  page_range: 5
  default_options:
    page_name: page
    sort_field_name: sort
    sort_direction_name: direction
    distinct: true
  template:
    pagination: 'pagination/custom_pagination.html.twig'
    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'