framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
#        envelope:
#            sender: '%env(MAILER_SENDER)%'
#        headers:
#            From: '%env(MAILER_FROM)%'
    profiler:
        collect: true